name: React CI/CD

# Only trigger, when the Docker build workflow succeeded !
on:
  workflow_run: 
    workflows: ["Docker CI/CD"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run Docker-pull && Docker-compose
      run: docker-compose pull && docker-compose -p mtgs87 -f /home/portofolio-project/Portoflio_2024/docker-compose.yml up -d

